### ISSUE TITLE
why the semantic image has a rigth shift?

### ISSUE THREAD

**Issue by huihuangz** [torrvision/crfasrnn#112]
I run the crfasrnn. the input and output as following:
![46](https://cloud.githubusercontent.com/assets/10891939/24044829/d337786a-0b14-11e7-9d78-dfa024aae0ac.png)

![46_output](https://cloud.githubusercontent.com/assets/10891939/24044842/ddfb7bb6-0b14-11e7-9997-96e1df3af3f5.png)

![24](https://cloud.githubusercontent.com/assets/10891939/24044911/24db885a-0b15-11e7-9fed-05de1ec8de47.jpg)

![24_output](https://cloud.githubusercontent.com/assets/10891939/24044921/2a5403e8-0b15-11e7-9ddf-7a1fdc8db98f.png)

why the semantic image has a right and botton shift?
Many thanks.

**Comment by bittnt** [comment]
I guess the reason is that the image padding or image cropping are done differently from its expectation or the crop layer has a wrong setting. I did not see any of these problems from our demo results though. http://www.robots.ox.ac.uk/~szheng/crfasrnndemo/classify_url?imageurl=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F10891939%2F24044829%2Fd337786a-0b14-11e7-9d78-dfa024aae0ac.png

**Comment by sadeepj** [comment]
This appears to be bug in the user code as we are not able to replicate it.
