### ISSUE TITLE
why the blobs[0] is batch_number=1, channel=1, channels_ X channels_ matrix?? What is channels_ in image

### ISSUE THREAD

**Issue by sharpstill** [torrvision/crfasrnn#131]
I notice that 
this->blobs_[0].reset(new Blob<Dtype>(1, 1, channels_, channels_));
this->blobs_[1].reset(new Blob<Dtype>(1, 1, channels_, channels_));
because 
blobs_[0] - spatial kernel weights, blobs_[1] - bilateral kernel weights, blobs_[2] - compatability matrix
so **why the blobs[0] is batch_number=1, channel=1, channels_ X channels_ matrix??**

**Comment by sadeepj** [comment]
We have done this to make the implementation with the BLAS API easier. Essentially, blobs_[0] and blobs_[1] each contains a 21 x 21 matrix (blob dimensions 1 x 1 x 21 x 21). 

Only diagonal entries of blobs_[0] and blobs_[1] are absolutely needed since off-diagonal entries can be learned in the compatibility transform stage (blobs_[2]) as well. Diagonal entries of blobs_[0] and blobs_[1] (there are 21 diagonal entries in each) represent class-specific kernel weights as described in Section 4.3 of http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf.
